/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkloadViewRouteImport } from './routes/_app/workload-view'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTuitionRouteImport } from './routes/_app/tuition'
import { Route as AppTimeTrackingRouteImport } from './routes/_app/time-tracking'
import { Route as AppTeachersRouteImport } from './routes/_app/teachers'
import { Route as AppTaskAssignmentRouteImport } from './routes/_app/task-assignment'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppSprintPlanningRouteImport } from './routes/_app/sprint-planning'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppSalaryRouteImport } from './routes/_app/salary'
import { Route as AppRoomsRouteImport } from './routes/_app/rooms'
import { Route as AppPayrollRouteImport } from './routes/_app/payroll'
import { Route as AppMarketingRouteImport } from './routes/_app/marketing'
import { Route as AppLeaveApproveRouteImport } from './routes/_app/leave-approve'
import { Route as AppKanbanBoardRouteImport } from './routes/_app/kanban-board'
import { Route as AppHomeworkRouteImport } from './routes/_app/homework'
import { Route as AppGanttChartRouteImport } from './routes/_app/gantt-chart'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommentsThreadsRouteImport } from './routes/_app/comments-threads'
import { Route as AppClassesRouteImport } from './routes/_app/classes'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAttendanceTrackingRouteImport } from './routes/_app/attendance-tracking'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppMarketingSourcesRouteImport } from './routes/_app/marketing.sources'
import { Route as AppMarketingReportsRouteImport } from './routes/_app/marketing.reports'
import { Route as AppMarketingPromotionsRouteImport } from './routes/_app/marketing.promotions'
import { Route as AppMarketingLeadsRouteImport } from './routes/_app/marketing.leads'
import { Route as AppMarketingFollowUpRouteImport } from './routes/_app/marketing.follow-up'
import { Route as AppMarketingCampaignsRouteImport } from './routes/_app/marketing.campaigns'
import { Route as AppAccountingPaymentsRouteImport } from './routes/_app/accounting.payments'
import { Route as AppAccountingExpensesRouteImport } from './routes/_app/accounting.expenses'
import { Route as AppAccountingBalanceSheetRouteImport } from './routes/_app/accounting.balance-sheet'
import { Route as AppMarketingLeadsIdRouteImport } from './routes/_app/marketing.leads.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkloadViewRoute = AppWorkloadViewRouteImport.update({
  id: '/workload-view',
  path: '/workload-view',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTuitionRoute = AppTuitionRouteImport.update({
  id: '/tuition',
  path: '/tuition',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeTrackingRoute = AppTimeTrackingRouteImport.update({
  id: '/time-tracking',
  path: '/time-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppTaskAssignmentRoute = AppTaskAssignmentRouteImport.update({
  id: '/task-assignment',
  path: '/task-assignment',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSprintPlanningRoute = AppSprintPlanningRouteImport.update({
  id: '/sprint-planning',
  path: '/sprint-planning',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaryRoute = AppSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveApproveRoute = AppLeaveApproveRouteImport.update({
  id: '/leave-approve',
  path: '/leave-approve',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanBoardRoute = AppKanbanBoardRouteImport.update({
  id: '/kanban-board',
  path: '/kanban-board',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeworkRoute = AppHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AppRoute,
} as any)
const AppGanttChartRoute = AppGanttChartRouteImport.update({
  id: '/gantt-chart',
  path: '/gantt-chart',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommentsThreadsRoute = AppCommentsThreadsRouteImport.update({
  id: '/comments-threads',
  path: '/comments-threads',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceTrackingRoute = AppAttendanceTrackingRouteImport.update({
  id: '/attendance-tracking',
  path: '/attendance-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingSourcesRoute = AppMarketingSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppMarketingReportsRoute = AppMarketingReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppMarketingPromotionsRoute = AppMarketingPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppMarketingLeadsRoute = AppMarketingLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppMarketingFollowUpRoute = AppMarketingFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppMarketingCampaignsRoute = AppMarketingCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppAccountingPaymentsRoute = AppAccountingPaymentsRouteImport.update({
  id: '/accounting/payments',
  path: '/accounting/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingExpensesRoute = AppAccountingExpensesRouteImport.update({
  id: '/accounting/expenses',
  path: '/accounting/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingBalanceSheetRoute =
  AppAccountingBalanceSheetRouteImport.update({
    id: '/accounting/balance-sheet',
    path: '/accounting/balance-sheet',
    getParentRoute: () => AppRoute,
  } as any)
const AppMarketingLeadsIdRoute = AppMarketingLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMarketingLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AppAttendanceRoute
  '/attendance-tracking': typeof AppAttendanceTrackingRoute
  '/audit': typeof AppAuditRoute
  '/classes': typeof AppClassesRoute
  '/comments-threads': typeof AppCommentsThreadsRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/gantt-chart': typeof AppGanttChartRoute
  '/homework': typeof AppHomeworkRoute
  '/kanban-board': typeof AppKanbanBoardRoute
  '/leave-approve': typeof AppLeaveApproveRoute
  '/marketing': typeof AppMarketingRouteWithChildren
  '/payroll': typeof AppPayrollRoute
  '/rooms': typeof AppRoomsRoute
  '/salary': typeof AppSalaryRoute
  '/schedule': typeof AppScheduleRoute
  '/sprint-planning': typeof AppSprintPlanningRoute
  '/students': typeof AppStudentsRoute
  '/task-assignment': typeof AppTaskAssignmentRoute
  '/teachers': typeof AppTeachersRoute
  '/time-tracking': typeof AppTimeTrackingRoute
  '/tuition': typeof AppTuitionRoute
  '/users': typeof AppUsersRoute
  '/workload-view': typeof AppWorkloadViewRoute
  '/accounting/balance-sheet': typeof AppAccountingBalanceSheetRoute
  '/accounting/expenses': typeof AppAccountingExpensesRoute
  '/accounting/payments': typeof AppAccountingPaymentsRoute
  '/marketing/campaigns': typeof AppMarketingCampaignsRoute
  '/marketing/follow-up': typeof AppMarketingFollowUpRoute
  '/marketing/leads': typeof AppMarketingLeadsRouteWithChildren
  '/marketing/promotions': typeof AppMarketingPromotionsRoute
  '/marketing/reports': typeof AppMarketingReportsRoute
  '/marketing/sources': typeof AppMarketingSourcesRoute
  '/marketing/leads/$id': typeof AppMarketingLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AppAttendanceRoute
  '/attendance-tracking': typeof AppAttendanceTrackingRoute
  '/audit': typeof AppAuditRoute
  '/classes': typeof AppClassesRoute
  '/comments-threads': typeof AppCommentsThreadsRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/gantt-chart': typeof AppGanttChartRoute
  '/homework': typeof AppHomeworkRoute
  '/kanban-board': typeof AppKanbanBoardRoute
  '/leave-approve': typeof AppLeaveApproveRoute
  '/marketing': typeof AppMarketingRouteWithChildren
  '/payroll': typeof AppPayrollRoute
  '/rooms': typeof AppRoomsRoute
  '/salary': typeof AppSalaryRoute
  '/schedule': typeof AppScheduleRoute
  '/sprint-planning': typeof AppSprintPlanningRoute
  '/students': typeof AppStudentsRoute
  '/task-assignment': typeof AppTaskAssignmentRoute
  '/teachers': typeof AppTeachersRoute
  '/time-tracking': typeof AppTimeTrackingRoute
  '/tuition': typeof AppTuitionRoute
  '/users': typeof AppUsersRoute
  '/workload-view': typeof AppWorkloadViewRoute
  '/accounting/balance-sheet': typeof AppAccountingBalanceSheetRoute
  '/accounting/expenses': typeof AppAccountingExpensesRoute
  '/accounting/payments': typeof AppAccountingPaymentsRoute
  '/marketing/campaigns': typeof AppMarketingCampaignsRoute
  '/marketing/follow-up': typeof AppMarketingFollowUpRoute
  '/marketing/leads': typeof AppMarketingLeadsRouteWithChildren
  '/marketing/promotions': typeof AppMarketingPromotionsRoute
  '/marketing/reports': typeof AppMarketingReportsRoute
  '/marketing/sources': typeof AppMarketingSourcesRoute
  '/marketing/leads/$id': typeof AppMarketingLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/attendance-tracking': typeof AppAttendanceTrackingRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/comments-threads': typeof AppCommentsThreadsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/gantt-chart': typeof AppGanttChartRoute
  '/_app/homework': typeof AppHomeworkRoute
  '/_app/kanban-board': typeof AppKanbanBoardRoute
  '/_app/leave-approve': typeof AppLeaveApproveRoute
  '/_app/marketing': typeof AppMarketingRouteWithChildren
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/salary': typeof AppSalaryRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/sprint-planning': typeof AppSprintPlanningRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/task-assignment': typeof AppTaskAssignmentRoute
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/time-tracking': typeof AppTimeTrackingRoute
  '/_app/tuition': typeof AppTuitionRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/workload-view': typeof AppWorkloadViewRoute
  '/_app/accounting/balance-sheet': typeof AppAccountingBalanceSheetRoute
  '/_app/accounting/expenses': typeof AppAccountingExpensesRoute
  '/_app/accounting/payments': typeof AppAccountingPaymentsRoute
  '/_app/marketing/campaigns': typeof AppMarketingCampaignsRoute
  '/_app/marketing/follow-up': typeof AppMarketingFollowUpRoute
  '/_app/marketing/leads': typeof AppMarketingLeadsRouteWithChildren
  '/_app/marketing/promotions': typeof AppMarketingPromotionsRoute
  '/_app/marketing/reports': typeof AppMarketingReportsRoute
  '/_app/marketing/sources': typeof AppMarketingSourcesRoute
  '/_app/marketing/leads/$id': typeof AppMarketingLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/attendance-tracking'
    | '/audit'
    | '/classes'
    | '/comments-threads'
    | '/dashboard'
    | '/employees'
    | '/gantt-chart'
    | '/homework'
    | '/kanban-board'
    | '/leave-approve'
    | '/marketing'
    | '/payroll'
    | '/rooms'
    | '/salary'
    | '/schedule'
    | '/sprint-planning'
    | '/students'
    | '/task-assignment'
    | '/teachers'
    | '/time-tracking'
    | '/tuition'
    | '/users'
    | '/workload-view'
    | '/accounting/balance-sheet'
    | '/accounting/expenses'
    | '/accounting/payments'
    | '/marketing/campaigns'
    | '/marketing/follow-up'
    | '/marketing/leads'
    | '/marketing/promotions'
    | '/marketing/reports'
    | '/marketing/sources'
    | '/marketing/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/attendance-tracking'
    | '/audit'
    | '/classes'
    | '/comments-threads'
    | '/dashboard'
    | '/employees'
    | '/gantt-chart'
    | '/homework'
    | '/kanban-board'
    | '/leave-approve'
    | '/marketing'
    | '/payroll'
    | '/rooms'
    | '/salary'
    | '/schedule'
    | '/sprint-planning'
    | '/students'
    | '/task-assignment'
    | '/teachers'
    | '/time-tracking'
    | '/tuition'
    | '/users'
    | '/workload-view'
    | '/accounting/balance-sheet'
    | '/accounting/expenses'
    | '/accounting/payments'
    | '/marketing/campaigns'
    | '/marketing/follow-up'
    | '/marketing/leads'
    | '/marketing/promotions'
    | '/marketing/reports'
    | '/marketing/sources'
    | '/marketing/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/attendance'
    | '/_app/attendance-tracking'
    | '/_app/audit'
    | '/_app/classes'
    | '/_app/comments-threads'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/gantt-chart'
    | '/_app/homework'
    | '/_app/kanban-board'
    | '/_app/leave-approve'
    | '/_app/marketing'
    | '/_app/payroll'
    | '/_app/rooms'
    | '/_app/salary'
    | '/_app/schedule'
    | '/_app/sprint-planning'
    | '/_app/students'
    | '/_app/task-assignment'
    | '/_app/teachers'
    | '/_app/time-tracking'
    | '/_app/tuition'
    | '/_app/users'
    | '/_app/workload-view'
    | '/_app/accounting/balance-sheet'
    | '/_app/accounting/expenses'
    | '/_app/accounting/payments'
    | '/_app/marketing/campaigns'
    | '/_app/marketing/follow-up'
    | '/_app/marketing/leads'
    | '/_app/marketing/promotions'
    | '/_app/marketing/reports'
    | '/_app/marketing/sources'
    | '/_app/marketing/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workload-view': {
      id: '/_app/workload-view'
      path: '/workload-view'
      fullPath: '/workload-view'
      preLoaderRoute: typeof AppWorkloadViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tuition': {
      id: '/_app/tuition'
      path: '/tuition'
      fullPath: '/tuition'
      preLoaderRoute: typeof AppTuitionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/time-tracking': {
      id: '/_app/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof AppTimeTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/task-assignment': {
      id: '/_app/task-assignment'
      path: '/task-assignment'
      fullPath: '/task-assignment'
      preLoaderRoute: typeof AppTaskAssignmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sprint-planning': {
      id: '/_app/sprint-planning'
      path: '/sprint-planning'
      fullPath: '/sprint-planning'
      preLoaderRoute: typeof AppSprintPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salary': {
      id: '/_app/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AppSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-approve': {
      id: '/_app/leave-approve'
      path: '/leave-approve'
      fullPath: '/leave-approve'
      preLoaderRoute: typeof AppLeaveApproveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban-board': {
      id: '/_app/kanban-board'
      path: '/kanban-board'
      fullPath: '/kanban-board'
      preLoaderRoute: typeof AppKanbanBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/homework': {
      id: '/_app/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof AppHomeworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gantt-chart': {
      id: '/_app/gantt-chart'
      path: '/gantt-chart'
      fullPath: '/gantt-chart'
      preLoaderRoute: typeof AppGanttChartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comments-threads': {
      id: '/_app/comments-threads'
      path: '/comments-threads'
      fullPath: '/comments-threads'
      preLoaderRoute: typeof AppCommentsThreadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-tracking': {
      id: '/_app/attendance-tracking'
      path: '/attendance-tracking'
      fullPath: '/attendance-tracking'
      preLoaderRoute: typeof AppAttendanceTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/sources': {
      id: '/_app/marketing/sources'
      path: '/sources'
      fullPath: '/marketing/sources'
      preLoaderRoute: typeof AppMarketingSourcesRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/marketing/reports': {
      id: '/_app/marketing/reports'
      path: '/reports'
      fullPath: '/marketing/reports'
      preLoaderRoute: typeof AppMarketingReportsRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/marketing/promotions': {
      id: '/_app/marketing/promotions'
      path: '/promotions'
      fullPath: '/marketing/promotions'
      preLoaderRoute: typeof AppMarketingPromotionsRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/marketing/leads': {
      id: '/_app/marketing/leads'
      path: '/leads'
      fullPath: '/marketing/leads'
      preLoaderRoute: typeof AppMarketingLeadsRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/marketing/follow-up': {
      id: '/_app/marketing/follow-up'
      path: '/follow-up'
      fullPath: '/marketing/follow-up'
      preLoaderRoute: typeof AppMarketingFollowUpRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/marketing/campaigns': {
      id: '/_app/marketing/campaigns'
      path: '/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof AppMarketingCampaignsRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/accounting/payments': {
      id: '/_app/accounting/payments'
      path: '/accounting/payments'
      fullPath: '/accounting/payments'
      preLoaderRoute: typeof AppAccountingPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/expenses': {
      id: '/_app/accounting/expenses'
      path: '/accounting/expenses'
      fullPath: '/accounting/expenses'
      preLoaderRoute: typeof AppAccountingExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/balance-sheet': {
      id: '/_app/accounting/balance-sheet'
      path: '/accounting/balance-sheet'
      fullPath: '/accounting/balance-sheet'
      preLoaderRoute: typeof AppAccountingBalanceSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/leads/$id': {
      id: '/_app/marketing/leads/$id'
      path: '/$id'
      fullPath: '/marketing/leads/$id'
      preLoaderRoute: typeof AppMarketingLeadsIdRouteImport
      parentRoute: typeof AppMarketingLeadsRoute
    }
  }
}

interface AppMarketingLeadsRouteChildren {
  AppMarketingLeadsIdRoute: typeof AppMarketingLeadsIdRoute
}

const AppMarketingLeadsRouteChildren: AppMarketingLeadsRouteChildren = {
  AppMarketingLeadsIdRoute: AppMarketingLeadsIdRoute,
}

const AppMarketingLeadsRouteWithChildren =
  AppMarketingLeadsRoute._addFileChildren(AppMarketingLeadsRouteChildren)

interface AppMarketingRouteChildren {
  AppMarketingCampaignsRoute: typeof AppMarketingCampaignsRoute
  AppMarketingFollowUpRoute: typeof AppMarketingFollowUpRoute
  AppMarketingLeadsRoute: typeof AppMarketingLeadsRouteWithChildren
  AppMarketingPromotionsRoute: typeof AppMarketingPromotionsRoute
  AppMarketingReportsRoute: typeof AppMarketingReportsRoute
  AppMarketingSourcesRoute: typeof AppMarketingSourcesRoute
}

const AppMarketingRouteChildren: AppMarketingRouteChildren = {
  AppMarketingCampaignsRoute: AppMarketingCampaignsRoute,
  AppMarketingFollowUpRoute: AppMarketingFollowUpRoute,
  AppMarketingLeadsRoute: AppMarketingLeadsRouteWithChildren,
  AppMarketingPromotionsRoute: AppMarketingPromotionsRoute,
  AppMarketingReportsRoute: AppMarketingReportsRoute,
  AppMarketingSourcesRoute: AppMarketingSourcesRoute,
}

const AppMarketingRouteWithChildren = AppMarketingRoute._addFileChildren(
  AppMarketingRouteChildren,
)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAttendanceTrackingRoute: typeof AppAttendanceTrackingRoute
  AppAuditRoute: typeof AppAuditRoute
  AppClassesRoute: typeof AppClassesRoute
  AppCommentsThreadsRoute: typeof AppCommentsThreadsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppGanttChartRoute: typeof AppGanttChartRoute
  AppHomeworkRoute: typeof AppHomeworkRoute
  AppKanbanBoardRoute: typeof AppKanbanBoardRoute
  AppLeaveApproveRoute: typeof AppLeaveApproveRoute
  AppMarketingRoute: typeof AppMarketingRouteWithChildren
  AppPayrollRoute: typeof AppPayrollRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSalaryRoute: typeof AppSalaryRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSprintPlanningRoute: typeof AppSprintPlanningRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTaskAssignmentRoute: typeof AppTaskAssignmentRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTimeTrackingRoute: typeof AppTimeTrackingRoute
  AppTuitionRoute: typeof AppTuitionRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWorkloadViewRoute: typeof AppWorkloadViewRoute
  AppAccountingBalanceSheetRoute: typeof AppAccountingBalanceSheetRoute
  AppAccountingExpensesRoute: typeof AppAccountingExpensesRoute
  AppAccountingPaymentsRoute: typeof AppAccountingPaymentsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppAttendanceTrackingRoute: AppAttendanceTrackingRoute,
  AppAuditRoute: AppAuditRoute,
  AppClassesRoute: AppClassesRoute,
  AppCommentsThreadsRoute: AppCommentsThreadsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppGanttChartRoute: AppGanttChartRoute,
  AppHomeworkRoute: AppHomeworkRoute,
  AppKanbanBoardRoute: AppKanbanBoardRoute,
  AppLeaveApproveRoute: AppLeaveApproveRoute,
  AppMarketingRoute: AppMarketingRouteWithChildren,
  AppPayrollRoute: AppPayrollRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSalaryRoute: AppSalaryRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSprintPlanningRoute: AppSprintPlanningRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTaskAssignmentRoute: AppTaskAssignmentRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTimeTrackingRoute: AppTimeTrackingRoute,
  AppTuitionRoute: AppTuitionRoute,
  AppUsersRoute: AppUsersRoute,
  AppWorkloadViewRoute: AppWorkloadViewRoute,
  AppAccountingBalanceSheetRoute: AppAccountingBalanceSheetRoute,
  AppAccountingExpensesRoute: AppAccountingExpensesRoute,
  AppAccountingPaymentsRoute: AppAccountingPaymentsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
